### ISSUE TITLE
this is not the appropriate use of git

### ISSUE THREAD

**Issue by LickTheCheese** [icanotc/vincent-put-random-stuff-here#1]
git is a source code version/management system, nextcloud, google drive, the releases section of github etc would be a better option

on second thought, scratch that, microsoft bought github so pls fill your repos with large volumes of binaries pls thanks

**Comment by icanotc** [comment]
too bad

**Comment by LickTheCheese** [comment]
I am fully in support of you abusing git in this way because fuck microsoft lol
